name: catodo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  equatable: ^2.0.7
  flame: ^1.16.0
  flame_tiled: ^1.18.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  audioplayers: ^6.4.0
  just_audio: ^0.10.0
  fl_chart: ^0.71.0
  wakelock_plus: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/
    - assets/images/
    - assets/images/cat/
    - assets/images/cat/Cats/
    - assets/images/cat/Cats/Sprites/
    - assets/sounds/
